"""Create all initial tables based on updated ERD

Revision ID: 1a0e51405d51
Revises: 
Create Date: 2025-06-24 03:42:25.642165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0e51405d51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_pensiun',
    sa.Column('id_jenis_pensiun', sa.Integer(), nullable=False),
    sa.Column('nama_jenis_pensiun', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_jenis_pensiun'),
    sa.UniqueConstraint('nama_jenis_pensiun')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cluster',
    sa.Column('id_cluster', sa.Integer(), nullable=False),
    sa.Column('tabel_cluster', sa.String(length=255), nullable=False),
    sa.Column('tanggal_klasterisasi', sa.DateTime(), nullable=True),
    sa.Column('dijalankan_oleh_id', sa.Integer(), nullable=False),
    sa.Column('k_value', sa.Integer(), nullable=False),
    sa.Column('fitur_digunakan', sa.Text(), nullable=True),
    sa.Column('silhouette_score', sa.Float(), nullable=True),
    sa.Column('jumlah_data_dicluster', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dijalankan_oleh_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_cluster')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_pensiun', sa.String(length=100), nullable=False),
    sa.Column('penerima', sa.String(length=255), nullable=False),
    sa.Column('status_pensiun', sa.String(length=100), nullable=True),
    sa.Column('cabang', sa.String(length=100), nullable=True),
    sa.Column('mitra', sa.String(length=100), nullable=True),
    sa.Column('status_auten', sa.String(length=50), nullable=True),
    sa.Column('bulan', sa.Integer(), nullable=True),
    sa.Column('usia', sa.Integer(), nullable=True),
    sa.Column('jenis_pekerjaan', sa.String(length=100), nullable=True),
    sa.Column('waktu_upload', sa.DateTime(), nullable=True),
    sa.Column('user_input_id', sa.Integer(), nullable=False),
    sa.Column('jenis_pensiun_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('cluster_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['jenis_pensiun_id'], ['jenis_pensiun.id_jenis_pensiun'], ),
    sa.ForeignKeyConstraint(['user_input_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomor_pensiun')
    )
    op.create_table('laporan_analisis',
    sa.Column('id_laporan', sa.Integer(), nullable=False),
    sa.Column('total_data', sa.Integer(), nullable=True),
    sa.Column('rata_rata_usia', sa.Float(), nullable=True),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('jenis_pensiun_id', sa.Integer(), nullable=True),
    sa.Column('dibuat_oleh_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id_cluster'], ),
    sa.ForeignKeyConstraint(['dibuat_oleh_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['jenis_pensiun_id'], ['jenis_pensiun.id_jenis_pensiun'], ),
    sa.PrimaryKeyConstraint('id_laporan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laporan_analisis')
    op.drop_table('data')
    op.drop_table('cluster')
    op.drop_table('users')
    op.drop_table('jenis_pensiun')
    # ### end Alembic commands ###
